global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kafka-jmx'
    static_configs:
      - targets: ['kafka:9101']

  - job_name: 'order-processor-metrics'
    static_configs:
      - targets: ['order-processor:8000']
    scrape_interval: 5s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']