global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9101']

  - job_name: 'spark-master'
    static_configs:
      - targets: ['spark-master:8080']

  - job_name: 'spark-worker-1'
    static_configs:
      - targets: ['spark-worker-1:8081']

  - job_name: 'spark-worker-2'
    static_configs:
      - targets: ['spark-worker-2:8081']