services:
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: flink-kafka
    ports:
      - "9093:9092"
      - "9102:9101"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9093'
      KAFKA_METRICS_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: kafka:29092
      KAFKA_CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      KAFKA_CONFLUENT_METRICS_ENABLE: 'true'
      KAFKA_CONFLUENT_SUPPORT_CUSTOMER_ID: anonymous
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      EXTRA_ARGS: '-javaagent:/usr/share/java/cp-base-new/jmx_prometheus_javaagent-0.18.0.jar=9102:/etc/prometheus/prometheus.yml'
      JMX_PROMETHEUS_PORT: 9102
      KAFKA_OPTS: '-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=localhost'
    volumes:
      - ./kafka-data:/tmp/kraft-combined-logs
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - flink-network
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list"]
      interval: 30s
      timeout: 10s
      retries: 3

  jobmanager:
    image: flink:1.19
    container_name: flink-jobmanager
    ports:
      - "8085:8081"  # Flink Web UI
      - "6123:6123"  # JobManager RPC
      - "9249:9249"  # Metrics port
    command: jobmanager
    environment:
      - FLINK_PROPERTIES=jobmanager.rpc.address: jobmanager
        jobmanager.rpc.port: 6123
        jobmanager.memory.process.size: 1600m
        taskmanager.memory.process.size: 1728m
        taskmanager.numberOfTaskSlots: 2
        parallelism.default: 2
        jobmanager.execution.failover-strategy: region
        restart-strategy: fixed-delay
        restart-strategy.fixed-delay.attempts: 3
        restart-strategy.fixed-delay.delay: 10 s
        execution.checkpointing.interval: 10s
        execution.checkpointing.min-pause: 5s
        state.backend: filesystem
        state.checkpoints.dir: file:///tmp/flink-checkpoints
        state.savepoints.dir: file:///tmp/flink-savepoints
        metrics.reporter.prom.class: org.apache.flink.metrics.prometheus.PrometheusReporter
        metrics.reporter.prom.port: 9249
    volumes:
      - ./flink-logs:/opt/flink/log
      - ./order-processor:/opt/flink/jobs
    networks:
      - flink-network

  taskmanager-1:
    image: flink:1.19
    container_name: flink-taskmanager-1
    ports:
      - "6124:6121"
      - "9250:9249"
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - FLINK_PROPERTIES=jobmanager.rpc.address: jobmanager
        jobmanager.rpc.port: 6123
        taskmanager.memory.process.size: 1728m
        taskmanager.numberOfTaskSlots: 2
        taskmanager.rpc.port: 6121
        metrics.reporter.prom.class: org.apache.flink.metrics.prometheus.PrometheusReporter
        metrics.reporter.prom.port: 9249
    volumes:
      - ./flink-logs:/opt/flink/log
      - ./order-processor:/opt/flink/jobs
    networks:
      - flink-network

  taskmanager-2:
    image: flink:1.19
    container_name: flink-taskmanager-2
    ports:
      - "6125:6121"
      - "9251:9249"
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - FLINK_PROPERTIES=jobmanager.rpc.address: jobmanager
        jobmanager.rpc.port: 6123
        taskmanager.memory.process.size: 1728m
        taskmanager.numberOfTaskSlots: 2
        taskmanager.rpc.port: 6121
        metrics.reporter.prom.class: org.apache.flink.metrics.prometheus.PrometheusReporter
        metrics.reporter.prom.port: 9249
    volumes:
      - ./flink-logs:/opt/flink/log
      - ./order-processor:/opt/flink/jobs
    networks:
      - flink-network

  order-generator:
    build:
      context: ./order-generator
      dockerfile: Dockerfile
    container_name: flink-order-generator
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - ORDERS_PER_SECOND=10
    networks:
      - flink-network
    depends_on:
      kafka:
        condition: service_healthy

  order-processor:
    build:
      context: ./order-processor
      dockerfile: Dockerfile
    container_name: flink-order-processor
    ports:
      - "9252:9249"  # Metrics port
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - JOBMANAGER_RPC_ADDRESS=jobmanager
    volumes:
      - ./metrics:/app/metrics
    networks:
      - flink-network
    depends_on:
      - jobmanager
      - kafka

  prometheus:
    image: prom/prometheus:latest
    container_name: flink-prometheus
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - flink-network

  grafana:
    image: grafana/grafana:latest
    container_name: flink-grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - flink-grafana-storage:/var/lib/grafana
    networks:
      - flink-network

networks:
  flink-network:
    driver: bridge

volumes:
  flink-grafana-storage: